### ISSUE TITLE
Rebuff not poping up

### ISSUE THREAD

**Issue by PrimeDamage** [WesBosch/ReBuff#2]
Rebuff not showing at all for me after putting the plugin repository in dalamaud settings? Not sure if there is something else to do after adding it in the experimental tab.

**Comment by WesBosch** [comment]
You may need to close and reopen the game for the plugin to appear

**Comment by PrimeDamage** [comment]
Just did it and still got nothing idk what im doing wrong, i put the url in the custom plugin area too

**Comment by WesBosch** [comment]
I'm not sure what the issue would be then, it appears on the repo and I'm able to install it from there. Do you have the repo in the first section of the experimental tab or the second? (It should be in the second, the first section is for local dll files)

**Comment by PrimeDamage** [comment]
the second one for custom

**Comment by WesBosch** [comment]
The only other issues I could think of are if you're not searching for rebuff in the "all plugins" section, or if you still have xivauras installed that might cause a conflict since both plugins should currently use the same internal name
