### ISSUE TITLE
install q

### ISSUE THREAD

**Issue by gerrykoh** [WesBosch/ReBuff#4]
hi! i added the repo to the experimental tab but rebuff is not showing up. do i need any options checked or something? also, after its installed can i remove the xa plugin?

thank you for doing this!

**Comment by WesBosch** [comment]
You may need to remove Xivauras and it's repo, then restart the game before Rebuff will show up in the list. the plugin now uses the same internal name as Xivauras so they can't coexist, but it should automagically pick up your existing configuration. It may be a good idea to make an export code of your stuff beforehand just in case. 

This is a new set up and it works for me, but I don't know if it works for everyone else, so please let me know how it goes!

**Comment by gerrykoh** [comment]
thank you! how would i export the xivauras config if the plugin doesn't load?

**Comment by WesBosch** [comment]
Xivauras has an export function for pretty much every element, including groups to batch copy your presets. Should be one of the buttons on the bottom right of the main window

**Comment by gerrykoh** [comment]
thanks! what i mean is that the xa plugin won't load since 6.4 so there is no way to export its config right? and if i uninstall xa before installing rebuff then the xa config goes away when the plugin is uninstalled i think?

**Comment by WesBosch** [comment]
https://github.com/Tischel/XIVAuras

Tischel's fork is updated for 6.4 and is being maintained as the official release of xivauras currently. Using this fork will allow you to use xivauras on 6.4, you can then choose to either keep using that fork or switch to mine.

**Comment by gerrykoh** [comment]
i see, thank you!

**Comment by gerrykoh** [comment]
i've upgraded to the working 6.4 XA and then have switched over to your fork. thank you for your help!
