### ISSUE TITLE
FPS -20

### ISSUE THREAD

**Issue by nixglacie** [WesBosch/ReBuff#7]
The fps is constantly around 40 for me when using RB. I tried to go with it cuz i like indicators but sometimes it drops even to 20 during combat.

I read from release notes "When many elements are created, there may be noticable frame drops. This probably isn't fixable tbh" but its just too much so i had to go back to XA and make something close to indicators with solid color icons ( https://prnt.sc/SVQRN2q9otiz )

**Comment by WesBosch** [comment]
Yeah, it's a known issue, most likely dure to how bars and indicators are drawn as pieces (rather than simple icons and rectangles) I'm afraid there isn't much I can do to fix it currently
